services:
  web:
    build: .
    ports:
      - "3001:3000"
    environment:
      PIDFILE: /tmp/pids/server.pid
    volumes:
      - .:/usr/src
    tmpfs:
      - /tmp/pids
    command: rails s -b 0.0.0.0
